INSERT INTO PUBLIC.CUISINE_TYPE (TYPE_NAME) VALUES ('French');
INSERT INTO PUBLIC.CUISINE_TYPE (TYPE_NAME) VALUES ('Italian');
INSERT INTO PUBLIC.CUISINE_TYPE (TYPE_NAME) VALUES ('Chinese');

INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Flour');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Milk');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Eggs');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Potato');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Carrot');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Chicken');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Herbs');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Water');
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_NAME) VALUES ('Pasta');

INSERT INTO PUBLIC.INSTRUCTION (INSTRUCTION) VALUES ('Mix everything together, bake at 200C for 20 minutes.');
INSERT INTO PUBLIC.INSTRUCTION (INSTRUCTION) VALUES ('Add pasta to boiling water, cook for 5-7 minutes.');

INSERT INTO PUBLIC.RECIPE (CUISINE_TYPE_ID, INSTRUCTION_ID, RECIPE_NAME, DATE_ADDED, DESCRIPTION) VALUES (1, 1, 'Bread', '2025-09-01', 'Simple bread.');
INSERT INTO PUBLIC.RECIPE (CUISINE_TYPE_ID, INSTRUCTION_ID, RECIPE_NAME, DATE_ADDED, DESCRIPTION) VALUES (2, 2, 'Boiled pasta', '2025-09-01', 'Simple pasta.');

INSERT INTO PUBLIC.RECIPE_INGREDIENTS (INGREDIENT_ID, RECIPE_ID, QUANTITY) VALUES (1, 1, '500g');
INSERT INTO PUBLIC.RECIPE_INGREDIENTS (INGREDIENT_ID, RECIPE_ID, QUANTITY) VALUES (2, 1, '100ml');
INSERT INTO PUBLIC.RECIPE_INGREDIENTS (INGREDIENT_ID, RECIPE_ID, QUANTITY) VALUES (3, 1, '4');
INSERT INTO PUBLIC.RECIPE_INGREDIENTS (INGREDIENT_ID, RECIPE_ID, QUANTITY) VALUES (8, 2, '500ml');
INSERT INTO PUBLIC.RECIPE_INGREDIENTS (INGREDIENT_ID, RECIPE_ID, QUANTITY) VALUES (9, 2, '100g');
